version: "3.9"
services:
  backupbeacon:
    build: .
    container_name: backupbeacon-app
    ports:
      - "18080:18080"
    volumes:
      - ./data:/app/data
      - ./backup-target:/backup-target
    restart: unless-stopped